Created a login and a registor pages according to instructions
tataNeonKnights/spotify_clone pull request #38
Opened 2023-12-30 14:38 UTC by Ravi2977

Feature 35 updates
1- created a login page with two filds email and password with a button

2024-01-01 19:18 UTC, LipiDey requested changes
Change the black border, decrease the font-weight, increase font sizes, also change the bg color.

2024-01-02 05:18 UTC, Akash9119 commented
just change the for with htmlFor.

2024-01-02 05:23 UTC, Akash9119 approved these changes
change for with HTMLFor.

2024-01-02 05:25 UTC, Akash9119 approved these changes

2024-01-02 05:29 UTC, closed without merging